<?php

use Faker\Guesser\Name;

return [
    
   "bank" => [
       "local_bank" => [
           "1" => "Bank of Singapore",
           "2" => "DBS Bank Limited",
           "3" => "POSB",
           "4" =>"OCBC Bank",
           "5" =>"United Overseas Bank Limited (UOB)",
       ],
       "foreign_bank" => [
            "6" => "Standard Chartered Singapore",
            "7" => "Bangkok Bank Public Company Limited",
            "8" => "Bank of America, National Association",
            "9" => "Bank of China Limited",
            "10" => "Bank of East Asia Limited, The",
            "11" => "Bank of India",
            "12" => "Bank of Tokyo-Mitsubishi UFJ Limited, The",
            "13" => "Calyon",
            "14" => "CIMB Bank",
            "15" => "Calyon",
            "16" => "Citibank Singapore",
            "17" => "Hongkong and Shanghai Banking Corporation Limited",
            "18" => "Maybank Singapore Limited",
            "19" => "Hong Leong Bank Berhad",
            "20" => "Indian Bank",
            "21" => "Indian Overseas Bank",
            "22" => "JPMorgan Chase Bank, National Association",
            "23" => "Ping An Bank",
            "24" => "PT Bank Mandiri (Persero) Tbk.",
            "25" => "PT Bank Negara Indonesia (Persero) Tbk.",
            "26" => "RHB Bank Berhad",
            "27" => "Sumitomo Mitsui Banking Corporation",
            "28" => "UCO Bank",
            "29" => "Australia and New Zealand Banking Group Limited",				
            "30" => "BNP Paribas",				
            "31" => "Standard Chartered Bank",				
            "32" => "State Bank of India",				
            "33" => "ICICI Bank Limited",				
            "34" => "Industrial and Commercial Bank of China",				
            "35" => "Scotiabank",				
            "36" => "Barclays Bank PLC",				
            "37" => "Bayerische Hypo- und Vereinsbank Aktiengesellschaft",				
            "38" => "Chiao Tung Bank Company Limited",				
            "39" => "Commerzbank Aktiengesellschaft",				
            "40" => "Credit Suisse",				
            "41" => "Deutsche Bank Aktiengesellschaft",				
            "42" => "Dresdner Bank Aktiengesellschaft merged with Commerzbank in 2009",				
            "43" => "EFG Bank",				
            "44" => "First Commercial Bank Limited",				
            "45" => "Fortis Bank S.A./N.V.",				
            "46" => "Habib Bank Limited",				
            "47" => "ING Bank N.V.",				
            "48" => "KBC Bank N.V.",				
            "49" => "Korea Exchange Bank",				
            "50" => "Landesbank Baden-Wuerttemberg",				
            "51" => "Mizuho Bank Limited",				
            "52" => "Moscow Narodny Bank Limited",				
            "53" => "National Australia Bank Limited",				
            "54" => "National Bank of Kuwait SAK",				
            "55" => "Norddeutsche Landesbank",				
            "56" => "Northern Trust Company, The",				
            "57" => "Rabobank",				
            "58" => "Royal Bank of Scotland PLC, The",				
            "59" => "Sanpaolo IMI S.P.A.",				
            "60" => "Société Générale",				
            "61" => "State Street Bank and Trust Company",				
            "62" => "UBS AG",				
            "63" => "UFJ Bank Limited",				
            "64" => "WestLB Aktiengesellschaft",				
            "65" => "Absa Group",				
            "66" => "Agricultural Bank of China",				
            "67" => "Arab Bank",				
            "68" => "Banca di Roma",				
            "69" => "Banca Monte dei Paschi di Siena",				
            "70" => "Bank of Communications",				
            "71" => "Bank of Taiwan",				
            "72" => "BNY Mellon",				
            "73" => "Canadian Imperial Bank of Commerce",				
            "74" => "Chang Hwa Commercial Bank",				
            "75" => "China Construction Bank",				
            "76" => "Clariden Leu",				
            "77" => "Commonwealth Bank",				
            "78" => "Crédit Agricole",				
            "79" => "Crédit Industriel et Commercial",				
            "80" => "Banque Internationale à Luxembourg",				
            "81" => "DNB Bank ASA",				
            "82" => "DZ Bank Singapore Branch",				
            "83" => "Hana Bank",				
            "84" => "Hang Seng Bank Limited",				
            "85" => "HSH Nordbank",				
            "86" => "Hua Nan Commercial Bank",				
            "87" => "International Commercial Bank of China",				
            "88" => "Korea Development Bank",				
            "89" => "Krung Thai Bank",				
            "90" => "Land Bank of Taiwan",				
            "91" => "Lloyds Bank",				
            "92" => "Mitsubishi UFJ Trust and Banking Corporation",				
            "93" => "Natixis",				
            "94" => "Nordea Bank Finland",				
            "95" => "Norinchukin Bank",				
            "96" => "Philippine National Bank",				
            "97" => "Raiffeisen Zentralbank",				
            "98" => "Royal Bank of Canada",				
            "99" => "Shinhan Bank",				
            "100" => "Siam Commercial Bank",				
            "101" => "Skandinaviska Enskilda Banken",				
            "102" => "Sumitomo Mitsui Trust Holdings",				
            "103" => "Svenska Handelsbanken",				
            "104" => "Toronto Dominion Bank",				
            "105" => "Union de Banques Arabes et Francaises",				
            "106" => "Westpac",				
            "107" => "Woori Bank",
       ]
       
   ]

];
